name: llm-lesson
channels: 
  - conda-forge
dependencies:
  - python=3.10.6
  - git
  - anaconda
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - -r requirements.txt